### ISSUE TITLE
发现一个 bug

### ISSUE THREAD

**Issue by WangXuan95** [thejinchao/jpeg_encoder#11]
你好，

感谢你提供的非常简洁的 JPEG 编码的代码，对理解该算法非常有帮助。

不过我发现一个小 bug：在所有的8*8分块的压缩流写入结束后，应该进行一个 "byte flush" 操作：例如，如果此时 newByte=10011000， newBytePos=2，说明有5个bit仍在 newByte 变量中（还没来得及写入jpg文件），那么你应该先把 newByte 写入文件中（有点像flush），然后再写入jpg文件结束符 0xFFD9。

目前这个问题会导致图片最右下角的 Cr 通道的 8x8 的分块解码失败，如果你仔细观察，会发现右下角的 8x8 分块的颜色有点奇怪，有网格的效果。

希望该建议能帮到你。

**Comment by thejinchao** [comment]
谢谢，改了
