### ISSUE TITLE
对量化部分有一点疑问

### ISSUE THREAD

**Issue by 0xbbdd** [thejinchao/jpeg_encoder#9]
在函数`_foword_FDC`中，这部分量化的处理为什么只涉及到了`m_YTable`，`m_CbCrTable`没有被用到，是不是代码有错？

```cpp
...
temp *= alpha_u*alpha_v/m_YTable[ZigZag[v*8+u]];
fdc_data[ZigZag[v*8+u]] = (short) ((short)(temp + 16384.5) - 16384);
...
```

**Comment by lemondante** [comment]
您好，我也发现了这个问题。
但是我试了一下 似乎不影响结果？

我现在遇到的问题是出来图像的颜色是粉红色，看起来应该是红色蓝色的偏移量有问题？不知道问题在哪里，我自己写了dct相关的部分 Huffman相关部分都是用的源代码....

**Comment by thejinchao** [comment]
谢谢，的确是，抱歉把错误的代码放了那么久

**Comment by zimmerman520** [comment]
目前我也发现出来的图像颜色是粉红色的，哪里出现问题了呢
